robotic_toy:
  choice:
    switch:
      toys: 1
      litterbox: 1
petty_generosity:
  choice:
    petty:
      food: 3
catnip_not_for_you:
  choice:
    petty:
      catnip: 3
toys_not_for_you:
  choice:
    petty:
      toys: 1
litterbox_not_for_you:
  choice:
    petty:
      litterbox: 1
buy_1_get_1_free:
  choice:
    generous:
      litterbox: 1
community_bargains:
  choice:
    generous:
      food: 2
catnip_bargains:
  choice:
    generous:
      catnip: 2
buy_1_toy_get_1_free:
  choice:
    generous:
      toys: 1
sketchy_food:
  choice:
    irritate:
      shift: -1
got_into_the_goods:
  choice:
    remove:
      catnip: 3
lost_in_the_void:
  choice:
    remove:
      catnip: 2
spoiled_salami:
  choice:
    remove:
      catnip: 3
i_didnt_already_eat_yet:
  choice:
    remove:
      catnip: 3
taking_your_shit:
  choice:
    remove:
      litterbox: 2
smuggling_the_goods:
  choice:
    remove:
      catnip: 4
pleasing_your_cat:
  choice:
    remove:
      food: 4
stolen_dreams:
  choice:
    remove:
      catnip: 2
cup_of_water:
  choice:
    switch:
      catnip: 2
      food: 2